window.AAN={objects:[
{id:82433,title:'Corset',maker:'Maison Léoty',date:'1891',institution:'The Metropolitan Museum of Art, Costume Institute',accession:'C.I.45.27a, b',claimIds:['C01'],image:'https://images.metmuseum.org/CRDImages/ci/original/DT200606.jpg',record:'https://www.metmuseum.org/art/collection/search/82433',license:'CC0',role:'constraint, posture, learned silhouette',alt:'Ivory satin Maison Léoty corset shown frontally against a neutral ground.'},
{id:173652,title:'Corset',maker:'Royal Worcester Corset Company',date:'ca. 1872',institution:'The Metropolitan Museum of Art',accession:'2009.300.6638a, b',claimIds:['C01'],image:'https://images.metmuseum.org/CRDImages/ci/original/50.105.17_CP2.jpg',record:'https://www.metmuseum.org/art/collection/search/173652',license:'CC0',role:'industrialized containment',alt:'Structured nineteenth-century corset with front fastening and shaped panels.'},
{id:158256,title:'Corset',maker:'Maker unknown',date:'1740–60',institution:'The Metropolitan Museum of Art',accession:'2009.300.3330',claimIds:['C01'],image:'https://images.metmuseum.org/CRDImages/ci/original/69.2.51_front_CP4.jpg',record:'https://www.metmuseum.org/art/collection/search/158256',license:'CC0',role:'body-shaping technology',alt:'Eighteenth-century stays with a pointed front, photographed flat.'},
{id:626019,title:'Costume Armor and Sword in the Classical Style',maker:'Hallé',date:'ca. 1788–90',institution:'The Metropolitan Museum of Art, Arms and Armor',accession:'1988.65.1–.2; 1995.93a, b',claimIds:['C04'],image:'https://images.metmuseum.org/CRDImages/aa/original/DT5896.jpg',record:'https://www.metmuseum.org/art/collection/search/626019',license:'CC0',role:'role, protection, theater, authority',alt:'Ornate classical-style costume armor and sword displayed vertically.'},
{id:227647,title:'Glove',maker:'Maker unknown',date:'ca. 1600',institution:'The Metropolitan Museum of Art',accession:'53.134',claimIds:[],image:'https://images.metmuseum.org/CRDImages/es/original/DP151922.jpg',record:'https://www.metmuseum.org/art/collection/search/227647',license:'CC0',role:'interface between hand and world',alt:'Single embroidered historical glove with an elaborate cuff.'},
{id:717582,title:'Hat',maker:'Maker unknown',date:'ca. 1830',institution:'The Metropolitan Museum of Art',accession:'2022.428.5',claimIds:['C04'],image:'https://images.metmuseum.org/CRDImages/ad/original/DP-14863-055.jpg',record:'https://www.metmuseum.org/art/collection/search/717582',license:'CC0',role:'head, identity, status',alt:'Tall black nineteenth-century hat shown in profile.'},
{id:436533,title:'Shoes',maker:'Vincent van Gogh',date:'1888',institution:'The Metropolitan Museum of Art',accession:'1992.374',claimIds:[],image:'https://images.metmuseum.org/CRDImages/ep/original/DT1947.jpg',record:'https://www.metmuseum.org/art/collection/search/436533',license:'CC0',role:'gait, labor, personhood',alt:'Van Gogh painting of a worn pair of brown leather shoes.'},
{id:23205,title:'Armor',maker:'Maker unknown',date:'ca. 1400–1450 and later',institution:'The Metropolitan Museum of Art, Arms and Armor',accession:'29.154.3',claimIds:['A02'],image:'https://images.metmuseum.org/CRDImages/aa/original/DP-46028-001.jpg',record:'https://www.metmuseum.org/art/collection/search/23205',license:'CC0',role:'literal protection, weight, articulated boundary',alt:'Italian steel armor with pointed breastplate, articulated limbs and helmet, shown frontally.'},
{id:27790,title:'Portions of a Costume Armor',maker:'Kolman Helmschmid',date:'ca. 1525',institution:'The Metropolitan Museum of Art, Arms and Armor',accession:'24.179; 26.188.1, .2; 29.158.363a, b',claimIds:['A03'],image:'https://images.metmuseum.org/CRDImages/aa/original/DP-22969-001.jpg',record:'https://www.metmuseum.org/art/collection/search/27790',license:'CC0',role:'dress, spectacle, status signal',alt:'Elaborately etched steel costume armor displayed frontally against a pale ground.'},
{id:22001,title:'Field Armor',maker:'Nuremberg armorer, maker unknown',date:'ca. 1525 and later',institution:'The Metropolitan Museum of Art, Arms and Armor',accession:'04.3.289',claimIds:['A01','A02'],image:'https://images.metmuseum.org/CRDImages/aa/original/DP341737.jpg',record:'https://www.metmuseum.org/art/collection/search/22001',license:'CC0',role:'mobility negotiated through protection',alt:'Fluted German field armor shown in three-quarter view with articulated joints and rounded helmet.'},
{id:24671,title:'Armor of Henry II, King of France',maker:'Decoration design by Jean Cousin the Elder; possibly Baptiste Pellerin',date:'ca. 1555',institution:'The Metropolitan Museum of Art, Arms and Armor',accession:'39.121a–n',claimIds:['A03'],image:'https://images.metmuseum.org/CRDImages/aa/original/DP256970.jpg',record:'https://www.metmuseum.org/art/collection/search/24671',license:'CC0',role:'authority made visible; parade rather than proof',alt:'Blackened and gilded French parade armor covered in dense scrolling decoration, shown frontally.'},
{id:22020,title:'Armor (Gusoku)',maker:'Maker unknown',date:'19th century',institution:'The Metropolitan Museum of Art, Arms and Armor',accession:'04.4.2',claimIds:['A01','A04'],image:'https://images.metmuseum.org/CRDImages/aa/original/DP264123.jpg',record:'https://www.metmuseum.org/art/collection/search/22020',license:'CC0',role:'layered identity, ritual and material memory',alt:'Japanese gusoku armor with horned helmet, lacquered plates, silk lacing and a patterned surcoat.'}
],claims:[
{id:'C01',claim:'A garment’s symbolic meaning plus physically wearing it may affect attention.',status:'disputed',measure:'Selective attention tasks',study:'Adam & Galinsky (2012)',boundary:'The famous lab-coat effect did not survive a preregistered direct replication.',doi:'https://doi.org/10.1016/j.jesp.2012.02.008'},
{id:'C02',claim:'The original lab-coat Stroop result was not reproduced.',status:'replication',measure:'Stroop performance',study:'Burns, Fox, Greenstein, Olbricht & Montgomery (2019)',boundary:'The preregistered direct replication concluded that any effect was too small for the original design to detect reliably. This does not prove clothing can never influence cognition.',doi:'https://doi.org/10.1016/j.jesp.2018.10.001'},
{id:'C03',claim:'The aggregate evidence is more qualified than the viral headline.',status:'qualified',measure:'Z-curve and meta-analysis',study:'C. Blaine Horton Jr., Hajo Adam & Adam D. Galinsky (online 2023; issue 2025)',boundary:'The authors found evidence consistent with some enclothed-cognition effects while also identifying weaker replicability in the earliest studies. That does not establish a universal garment effect.',doi:'https://doi.org/10.1177/01461672231182478'},
{id:'C04',claim:'Attire can operate as a social-status cue during interaction.',status:'supported',measure:'Behavioral and cardiovascular measures',study:'Kraus & Mendes (2014)',boundary:'Physiology is not identical to neural evidence.',doi:'https://doi.org/10.1037/xge0000023'},
{id:'A01',claim:'Clothing continuously supplies tactile, proprioceptive and thermal information; it can therefore change bodily experience.',status:'mechanism',measure:'Material-touch psychophysiology and sensory literature',study:'Bertheaux et al. (2020)',boundary:'Touching material samples is not the same as wearing a favorite outfit, and pupil response is not confidence.',doi:'https://doi.org/10.3389/fnhum.2019.00455'},
{id:'A02',claim:'Clothing can be experienced as a boundary between body and world.',status:'theory',measure:'Phenomenological analysis and testable hypotheses',study:'Ciaunica et al. (2021)',boundary:'This is a philosophical account informed by cognitive science, not a clinical trial proving that clothing regulates threat.',doi:'https://doi.org/10.3389/fpsyg.2021.613587'},
{id:'A03',claim:'Observers use dress when forming impressions about identity, traits and social roles.',status:'review',measure:'Person-perception literature review',study:'Hester & Hehman (2023)',boundary:'Being judged differently can change a social encounter; it does not show that the garment directly altered the wearer’s brain.',doi:'https://doi.org/10.1177/10888683231157961'},
{id:'A04',claim:'Some people describe clothing as self-expression, camouflage, mastery or pleasure.',status:'correlational',measure:'Self-report clothing practices and body-image measures',study:'Stolovy (2021)',boundary:'A convenience sample of Israeli women cannot establish causation or represent every culture, gender or body.',doi:'https://doi.org/10.3389/fpsyg.2021.719318'},
{id:'A05',claim:'“This outfit is my armor” is a meaningful report of experience, not a diagnosis or universal neuroscientific effect.',status:'experience',measure:'First-person reflection',study:'Reader field protocol; no population claim',boundary:'A personal effect may be genuine without revealing which mechanism caused it or predicting another person’s response.',doi:'/production/package-002-field-notes.md'}]};
window.filterEvidence=(claims,status,measure)=>claims.filter(c=>(status==='all'||c.status===status)&&(measure==='all'||c.measure.toLowerCase().includes(measure)));
