window.AAN={objects:[
{id:82433,title:'Corset',maker:'Maison Léoty',date:'1891',institution:'The Metropolitan Museum of Art, Costume Institute',accession:'C.I.45.27a, b',claimIds:['C01'],image:'https://images.metmuseum.org/CRDImages/ci/original/DT200606.jpg',record:'https://www.metmuseum.org/art/collection/search/82433',license:'CC0',role:'constraint, posture, learned silhouette',alt:'Ivory satin Maison Léoty corset shown frontally against a neutral ground.'},
{id:173652,title:'Corset',maker:'Royal Worcester Corset Company',date:'ca. 1872',institution:'The Metropolitan Museum of Art',accession:'2009.300.6638a, b',claimIds:['C01'],image:'https://images.metmuseum.org/CRDImages/ci/original/50.105.17_CP2.jpg',record:'https://www.metmuseum.org/art/collection/search/173652',license:'CC0',role:'industrialized containment',alt:'Structured nineteenth-century corset with front fastening and shaped panels.'},
{id:158256,title:'Corset',maker:'Maker unknown',date:'1740–60',institution:'The Metropolitan Museum of Art',accession:'2009.300.3330',claimIds:['C01'],image:'https://images.metmuseum.org/CRDImages/ci/original/69.2.51_front_CP4.jpg',record:'https://www.metmuseum.org/art/collection/search/158256',license:'CC0',role:'body-shaping technology',alt:'Eighteenth-century stays with a pointed front, photographed flat.'},
{id:626019,title:'Costume Armor and Sword in the Classical Style',maker:'Hallé',date:'ca. 1788–90',institution:'The Metropolitan Museum of Art, Arms and Armor',accession:'1988.65.1–.2; 1995.93a, b',claimIds:['C04'],image:'https://images.metmuseum.org/CRDImages/aa/original/DT5896.jpg',record:'https://www.metmuseum.org/art/collection/search/626019',license:'CC0',role:'role, protection, theater, authority',alt:'Ornate classical-style costume armor and sword displayed vertically.'},
{id:227647,title:'Glove',maker:'Maker unknown',date:'ca. 1600',institution:'The Metropolitan Museum of Art',accession:'53.134',claimIds:[],image:'https://images.metmuseum.org/CRDImages/es/original/DP151922.jpg',record:'https://www.metmuseum.org/art/collection/search/227647',license:'CC0',role:'interface between hand and world',alt:'Single embroidered historical glove with an elaborate cuff.'},
{id:717582,title:'Hat',maker:'Maker unknown',date:'ca. 1830',institution:'The Metropolitan Museum of Art',accession:'2022.428.5',claimIds:['C04'],image:'https://images.metmuseum.org/CRDImages/ad/original/DP-14863-055.jpg',record:'https://www.metmuseum.org/art/collection/search/717582',license:'CC0',role:'head, identity, status',alt:'Tall black nineteenth-century hat shown in profile.'},
{id:436533,title:'Shoes',maker:'Vincent van Gogh',date:'1888',institution:'The Metropolitan Museum of Art',accession:'1992.374',claimIds:[],image:'https://images.metmuseum.org/CRDImages/ep/original/DT1947.jpg',record:'https://www.metmuseum.org/art/collection/search/436533',license:'CC0',role:'gait, labor, personhood',alt:'Van Gogh painting of a worn pair of brown leather shoes.'}
],claims:[
{id:'C01',claim:'A garment’s symbolic meaning plus physically wearing it may affect attention.',status:'disputed',measure:'Selective attention tasks',study:'Adam & Galinsky (2012)',boundary:'The famous lab-coat effect did not survive a preregistered direct replication.',doi:'https://doi.org/10.1016/j.jesp.2012.02.008'},
{id:'C02',claim:'The original lab-coat Stroop result was not reproduced.',status:'replication',measure:'Stroop performance',study:'Burns, Fox, Greenstein & Montgomery (2019)',boundary:'A null replication does not prove clothing can never influence cognition.',doi:'https://doi.org/10.31234/osf.io/cj6kv'},
{id:'C03',claim:'The aggregate evidence is more qualified than the viral headline.',status:'qualified',measure:'Z-curve and meta-analysis',study:'C. Blaine Horton Jr., Hajo Adam & Adam D. Galinsky (2023)',boundary:'Effect sizes and publication selection constrain causal confidence.',doi:'https://doi.org/10.1177/01461672231182478'},
{id:'C04',claim:'Attire can operate as a social-status cue during interaction.',status:'supported',measure:'Behavioral and cardiovascular measures',study:'Kraus & Mendes (2014)',boundary:'Physiology is not identical to neural evidence.',doi:'https://doi.org/10.1037/xge0000023'}]};
window.filterEvidence=(claims,status,measure)=>claims.filter(c=>(status==='all'||c.status===status)&&(measure==='all'||c.measure.toLowerCase().includes(measure)));
